[package]
name = "transition-cpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cust = "0.3.2"
thiserror = "1.0.31"

[build-dependencies]
cuda_builder = "0.3.0"
